template:
    target: dev
    outputs:
        dev:
            type: "{{ env_var('DBT_ENV_TEMPLATE_CONN_TYPE') }}"
            method: "{{ env_var('DBT_ENV_TEMPLATE_TRINO_METHOD') }}"
            user: "{{ env_var('DBT_ENV_TEMPLATE_TRINO_USER') }}"
            host: "{{ env_var('DBT_ENV_TEMPLATE_TRINO_HOST') }}"
            catalog: "{{ env_var('DBT_ENV_TEMPLATE_TRINO_CATALOG') }}"
            schema: "{{ env_var('DBT_ENV_TEMPLATE_TRINO_SCHEMA') }}"
            port: 443
