template:
    target: dev
    outputs:
        prod:
            type: trino
            method: jwt
            jwt_token: ""
            host: "{{ env_var('DBT_ENV_TEMPLATE_TRINO_HOST') }}"
            catalog: template_developer
            schema: dbt_prod
            port: 443
        dev:
            type: trino
            method: oauth
            host: "{{ env_var('DBT_ENV_TEMPLATE_TRINO_HOST') }}"
            catalog: template_developer
            schema: "{{ env_var('DBT_ENV_TEMPLATE_TRINO_SCHEMA') }}"
            port: 443
        test:
            type: trino
            method: none
            user: dbt
            host: "{{ env_var('DBT_ENV_TEMPLATE_TRINO_HOST') }}"
            catalog: "{{ env_var('DBT_ENV_TEMPLATE_TRINO_CATALOG') }}"
            schema: "{{ env_var('DBT_ENV_TEMPLATE_TRINO_SCHEMA') }}"
            port: 443
