name: Add auth secrets for Temporal workflow
description: |
  This action retrieves the mandatory auth-secrets from the GitHub environment
  and creates a new Juju secret containing them.
  These are the secrets used to connect to the Temporal server.

inputs:
  temporal-encryption-key:
    description: Temporal encryption key
    required: true
  temporal-auth-provider:
    description: Temporal auth provider
    required: true
  temporal-service-account:
    description: Temporal service account JSON
    required: true
outputs:
  secret-id:
    description: Secret ID
    value: ${{ steps.auth-secrets.outputs.secret-id }}

runs:
  using: "composite"
  steps:
    - name: Add auth-secrets to Juju
      id: auth-secrets
      run: |
        # Add auth-secrets to Juju
        # Disable shell history
        set +x
        set -eu
        set +o history

        # To extract the secrets we must use the `"${...}"` syntax
        # Otherwise they are still encrypted
        if [[ -z "${TEMPORAL_ENCRYPTION_KEY}" ]] || [[ -z "${TEMPORAL_AUTH_PROVIDER}" || -z "${TEMPORAL_OIDC}" ]]; then
          echo "TEMPORAL_ENCRYPTION_KEY, TEMPORAL_AUTH_PROVIDER or TEMPORAL_OIDC is not set"
          echo "Please double-check the environment secrets."
          exit 1
        fi

        encryption_key="${TEMPORAL_ENCRYPTION_KEY}"
        auth_provider="${TEMPORAL_AUTH_PROVIDER}"

        fields=(type project_id private_key_id private_key client_email client_id auth_uri token_uri auth_provider_x509_cert_url client_x509_cert_url)
        for field in "${fields[@]}"; do
          declare "$field"="$(jq -r ".${field}" <<< "${TEMPORAL_OIDC}")"
        done

        source $HOME/.envrc
        secret_name="${WORKFLOW_NAME}-auth-secret"
        # Notice the quotes around $private_key, it is a multiline string
        if juju list-secrets | grep -F -q ${secret_name}; then
          # Secret already exists
          juju update-secret ${secret_name} \
              temporal-encryption-key=$encryption_key \
              auth-provider=$auth_provider \
              oidc-auth-type=$type \
              oidc-project-id=$project_id \
              oidc-private-key-id=$private_key_id \
              oidc-private-key="$private_key" \
              oidc-client-email=$client_email \
              oidc-client-id=$client_id \
              oidc-auth-uri=$auth_uri \
              oidc-token-uri=$token_uri \
              oidc-auth-cert-url=$auth_provider_x509_cert_url \
              oidc-client-cert-url=$client_x509_cert_url
        else
          # Create new secret
          juju add-secret ${secret_name} \
              temporal-encryption-key=$encryption_key \
              auth-provider=$auth_provider \
              oidc-auth-type=$type \
              oidc-project-id=$project_id \
              oidc-private-key-id=$private_key_id \
              oidc-private-key="$private_key" \
              oidc-client-email=$client_email \
              oidc-client-id=$client_id \
              oidc-auth-uri=$auth_uri \
              oidc-token-uri=$token_uri \
              oidc-auth-cert-url=$auth_provider_x509_cert_url \
              oidc-client-cert-url=$client_x509_cert_url
          juju grant-secret ${secret_name} ${WORKFLOW_NAME}-worker
        fi

        secret_id=$(juju list-secrets | grep -F ${secret_name} | awk '{print $1}')
        echo "secret-id=${secret_id}" >> $GITHUB_OUTPUT

      shell: bash
      env:
        WORKFLOW_NAME: ${{ github.event.repository.name }}
        TEMPORAL_ENCRYPTION_KEY: ${{ inputs.temporal-encryption-key }}
        TEMPORAL_AUTH_PROVIDER: ${{ inputs.temporal-auth-provider }}
        TEMPORAL_OIDC: ${{ inputs.temporal-service-account }}
