source:
  type: dbt
  config:
    manifest_path: "${DBT_PROJECT_ROOT}/target/manifest.json"
    catalog_path: "${DBT_PROJECT_ROOT}/target/catalog.json"
    # sources_path: "${DBT_PROJECT_ROOT}/target/sources_file.json" # optional for freshness
    run_results_paths:
      - "${DBT_PROJECT_ROOT}/target/run_results.json" # optional for recording dbt test results after running dbt test
    target_platform: trino

sink:
  type: datahub-rest
  config:
    server: ${DATAHUB_SERVER_STG}
    token: ${DATAHUB_TOKEN_STG}
