version: 2

models:
  - name: opportunity_contract
    description: lists the contracts with linked opportunities
    columns:
    - name: id
      description: salesforce id
    - name: accountid
      description: associated account id

sources:
  - name: marketing
    database: marketing
    schema: public
    tables:
    - name: salesforce_opportunity
    loaded_at_field: createddate
    freshness:
      warn_after: {count: 12, period: hour}
    - name: salesforce_leadhistory
    loaded_at_field: createddate
    freshness:
      warn_after: {count: 12, period: hour}
    - name: salesforce_lead
    loaded_at_field: createddate
    freshness:
      warn_after: {count: 12, period: hour}
    - name: salesforce_contact
    loaded_at_field: createddate
    freshness:
      warn_after: {count: 12, period: hour}
  - name: sales
    database: sales
    schema: public
    tables:
    - name: salesforce_contract
    loaded_at_field: createddate
    freshness:
      warn_after: {count: 12, period: hour}
