version: 2

models:
  - name: opportunity_contract
    description: lists the contracts with linked opportunities
    columns:
    - name: id
      description: salesforce id
    - name: accountid
      description: associated account id

sources:
  - name: marketing
    database: marketing
    schema: public
    tables:
    - name: salesforce_opportunity
  - name: sales
    database: sales
    schema: public
    tables:
    - name: salesforce_contract
