[sqlfluff]
templater = jinja
max_line_length = 100
# ignore dbt templating when running in github actions
ignore = templating

[sqlfluff:templater:jinja]
apply_dbt_builtins = True
load_macros_from_path = ../../

[sqlfluff:rules]
allow_scalar = True
single_table_references = consistent

[sqlfluff:indentation]
tab_space_size = 4
indent_unit = space
