{% macro account_owner_role_bucket(role_column) %} 
case
    when {{ role_column }} = 'Sales - Manager Americas - Enterprise'
    or {{ role_column }} = 'Sales - Americas - Enterprise' then 'Americas - Enterprise'
    when {{ role_column }} = 'Sales - Channel Director'
    or {{ role_column }} = 'Sales - Channel Alliances' then 'Channel Alliances'
    when {{ role_column }} = 'Sales - Silicon Alliances' then 'Silicon Alliances'
    when {{ role_column }} = 'Sales - VP Global Device'
    or {{ role_column }} = 'Sales - Device' then 'Device'
    when {{ role_column }} = 'Sales - Device BDR'
    or {{ role_column }} = 'Sales - Device' then 'Device'
    when {{ role_column }} = 'Sales - Global Accounts' then 'Global Accounts'
    when {{ role_column }} = 'Sales - VP Global IHV Alliances' then 'VP Global IHV Alliances'
    when {{ role_column }} = 'Sales - Renewals Americas'
    or {{ role_column }} = 'Sales - Renewals' then 'Renewals'
    when {{ role_column }} = 'Sales - APAC' then 'APAC'
    when {{ role_column }} = 'Sales - Manager - Americas - Public'
    or {{ role_column }} = 'Sales - Americas - Public' then 'Americas - Public'
    when {{ role_column }} = 'Sales - Manager - France, DACH, Spain, Italy'
    or {{ role_column }} = 'Sales - France, DACH, Spain, Italy' then 'France, DACH, Spain, Italy'
    when {{ role_column }} = 'Sales - Outside Alliances' then 'Outside Alliances'
    when {{ role_column }} = 'Sales - Cloud' then 'Cloud'
    when {{ role_column }} = 'Sales - France, DACH, Spain, Italy' then 'France, DACH, Spain, Italy'
    when {{ role_column }} = 'Sales - Manager Renewals and UK, Nordics, Emerging'
    or {{ role_column }} = 'Sales - Renewals' then 'Renewals'
    when {{ role_column }} = 'Sales - Telco'
    or {{ role_column }} = 'Sales - France, DACH, Spain, Italy' then 'France, DACH, Spain, Italy'
    when {{ role_column }} = 'Sales - Renewals ROW'
    or {{ role_column }} = 'Sales - Renewals' then 'Renewals'
    when {{ role_column }} = 'Sales - Channel Alliances' then 'Channel Alliances'
    when {{ role_column }} = 'Sales - Americas - Enterprise' then 'Americas - Enterprise'
    when {{ role_column }} = 'Sales - VP Global Datacenter' then 'VP Global Datacenter'
    when {{ role_column }} = 'Sales Ops User' then 'Sales Ops User'
    when {{ role_column }} = 'Sales - Device' then 'Device'
    when {{ role_column }} = 'Sales - UK, Nordics, Emerging' then 'UK, Nordics, Emerging'
    when {{ role_column }} = 'Commercial Systems' then 'Commercial Systems'
    when {{ role_column }} = 'Product Management' then 'Product Management'
    when {{ role_column }} = 'Sales - APAC Manager'
    or {{ role_column }} = 'Sales - APAC' then 'APAC'
    when {{ role_column }} = 'Sales - VP Silicon Alliances'
    or {{ role_column }} = 'Sales - Silicon Alliances' then 'Silicon Alliances'
    when {{ role_column }} = 'Integration' then 'Integration' --check
    when {{ role_column }} = 'Outbound SDR - AMER' then 'Outbound SDR - AMER'
    when {{ role_column }} = 'Sales Engineer-Datacenter' then 'Sales Engineer-Datacenter'
    when {{ role_column }} = 'Sales - VP Silicon IHV Alliances' then 'Sales - VP Silicon IHV Alliances'
    else 'Other'
end
{% endmacro %}