template:
    target: dev
    outputs:
        dev:
            type: trino
            method: ldap
            user: "{{ env_var('DBT_TEMPLATE_TRINO_USER') }}"
            password: "{{ env_var('DBT_ENV_SECRET_TEMPLATE_TRINO_PASSWORD') }}"
            host: trino.ps6.staging.canonical.com
            catalog: template_developer
            schema: public
            port: 443
