name: Add additional secrets to Juju
description: |
  This action retrieves all secrets from the GitHub environment
  and creates a new Juju secret containing them.
  It excludes the secrets used by the action itself (VAULT_*),
  the ones used for the Temporal server connection (TEMPORAL_*),
  and some added automatically by GitHub.

inputs:
  all-secrets:
    description: JSON object of all secrets ( toJSON(secrets) )
    required: true
  projects:
    description: List of dbt projects in the repository
    required: true
outputs:
  secret-id:
    description: Secret ID
    value: ${{ steps.secrets.outputs.secret-id }}

runs:
  using: "composite"
  steps:
    - name: Get secret keys and exclude ones used by the action or worker config
      id: secret-keys
      shell: bash
      run: |
        # Get secret keys and exclude ones used by the action or worker config
        # Disable shell history
        set +x
        set -eu
        set +o history

        secret_keys=$(jq -r 'keys[]' <<< "$ALL_SECRETS")
        exclude_patterns=(
          "TEMPORAL_*"
          "GITHUB_TOKEN"
          "K8S_CVE_WORKFLOW_JIRA_URL"
          "TICSAUTHTOKEN"
          "VAULT_APPROLE_ROLE_ID"
          "VAULT_APPROLE_SECRET_ID"
        )
        for pattern in "${exclude_patterns[@]}"; do
            secret_keys=$(echo "$secret_keys" | grep -v "$pattern")
        done

        # Save SECRET_KEYS to environment
        echo "SECRET_KEYS<<EOF" >> $GITHUB_ENV
        echo "$secret_keys" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
      env:
        ALL_SECRETS: ${{ inputs.all-secrets }}

    - name: Check for mandatory secrets and set defaults
      id: check-mandatory-secrets
      shell: bash
      run: |
        # Check for mandatory secrets and set defaults
        # Disable shell history
        set +x
        set -eu
        set +o history

        # Function to check if a variable is not in a list
        source ./.github/scripts/not-in-list.sh

        # Note that GITHUB_TOKEN is a GitHub default;
        # GIT_TOKEN is user-defined and what the workflow uses
        mandatory_secrets=(
          "GIT_TOKEN"
          "DATAHUB_TOKEN"
        )

        # Check for missing mandatory secrets and exit if any are missing
        for project in ${PROJECTS}; do
          upper_project=$(echo $project | tr '[:lower:]' '[:upper:]')
          mandatory_secrets+=("TRINO_OIDC_${upper_project}")
        done

        missing_secrets=false
        for secret in "${mandatory_secrets[@]}"; do
          if not_in_list "$secret" "${SECRET_KEYS}"; then
            echo "Missing mandatory secret: $secret"
            missing_secrets=true
          fi
        done
        if $missing_secrets; then
          echo "Please double-check the secrets."
          exit 1
        fi
      env:
        PROJECTS: ${{ inputs.projects }}

    - name: Add additional secrets to Juju
      id: secrets
      run: |
        # Add additional secrets to Juju
        # Disable shell history
        set +x
        set -eu
        set +o history

        secret_file="$HOME/${WORKFLOW_NAME}-secret.yaml"
        touch $secret_file

        for key in $SECRET_KEYS; do
          if [[ "$key" =~ "TRINO_OIDC_" ]]; then
            # Skip Trino OIDC secrets; check next loop
            continue
          fi

          lower_key=$(echo $key | tr '[:upper:]_' '[:lower:]-')
          value=$(jq -r ".$key" <<< "$ALL_SECRETS")
          echo "${lower_key}: ${value}" >> $secret_file
        done

        # Set Trino service account for each project in the repository
        for project in ${PROJECTS}; do
          upper_project=$(echo $project | tr '[:lower:]' '[:upper:]')
          project_trino="TRINO_OIDC_${upper_project}"
          service_account=$(jq -r ".$project_trino" <<< "${ALL_SECRETS}")

          # Convert the JSON into YAML and rename the property keys
          export PROJECT=$project
          yq -o=yaml '
          {
            ("trino-oidc-" + env(PROJECT) + "-auth-type"): .type,
            ("trino-oidc-" + env(PROJECT) + "-project-id"): .project_id,
            ("trino-oidc-" + env(PROJECT) + "-private-key-id"): .private_key_id,
            ("trino-oidc-" + env(PROJECT) + "-private-key"): (.private_key | tostring),
            ("trino-oidc-" + env(PROJECT) + "-client-email"): .client_email,
            ("trino-oidc-" + env(PROJECT) + "-client-id"): (.client_id | tostring),
            ("trino-oidc-" + env(PROJECT) + "-auth-uri"): .auth_uri,
            ("trino-oidc-" + env(PROJECT) + "-token-uri"): .token_uri,
            ("trino-oidc-" + env(PROJECT) + "-auth-cert-url"): .auth_provider_x509_cert_url,
            ("trino-oidc-" + env(PROJECT) + "-client-cert-url"): .client_x509_cert_url
          }
          ' <<< "$service_account" >> $secret_file
        done

        # Run the juju secret command and return the secret ID
        source $HOME/.envrc
        secret_name="${WORKFLOW_NAME}-secret"
        if juju list-secrets --format=json | jq -r ".[].name" | grep -Fxq "${secret_name}"; then
          # Secret already exists
          juju update-secret ${secret_name} \
              --file=$secret_file
        else
          # Create new secret
          juju add-secret ${secret_name} \
              --file=$secret_file
          juju grant-secret ${secret_name} ${WORKFLOW_NAME}-worker
        fi
        rm $secret_file
        secret_id=$(juju list-secrets | grep -F ${secret_name} | awk '{print $1}')
        echo "secret-id=${secret_id}" >> $GITHUB_OUTPUT
      shell: bash
      env:
        WORKFLOW_NAME: ${{ github.event.repository.name }}
        ALL_SECRETS: ${{ inputs.all-secrets }}
        PROJECTS: ${{ inputs.projects }}
