# Name your project! Generally speaking, it should be the same name
# as the data catalog you're writing to.
name: 'jira'
version: '1.0.0'
config-version: 2

# This value *must* match the directory name.
profile: 'jira'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

flags:
  require_certificate_validation: True

# In dbt, the default materialization is `view`.
# However, this is not supported by Trino.
# Thus, we materialize all models we wish to keep as tables.
# Intermediary models, which serve as layers between the raw data
# and the final model, are ephemeral.
models:
  jira:
    staging:
      +materialized: table
    intermediate:
      +materialized: ephemeral
    marts:
      +materialized: table

# Seeds are used to populate models with static data from e.g. CSV files.
# seeds:
#   jira:
#     +enabled: true
#     +schema: seed_data
