jira:
    target: prod
    outputs:
        prod:
            type: trino
            method: jwt
            jwt_token: "{{ env_var('DBT_ENV_SECRET_TRINO_TOKEN') }}"
            host: "{{ env_var('DBT_ENV_JIRA_TRINO_HOST') }}"
            catalog: enterprise_eng_ws_developer
            schema: dbt_prod
            port: 443
        dev:
            type: trino
            method: jwt
            jwt_token: "{{ env_var('DBT_ENV_SECRET_TRINO_TOKEN') }}"
            host: "{{ env_var('DBT_ENV_JIRA_TRINO_HOST') }}"
            catalog: enterprise_eng_ws_developer
            schema: dbt_dev
            port: 443
        test:
            type: trino
            method: oauth
            host: "{{ env_var('DBT_ENV_JIRA_TRINO_HOST') }}"
            catalog: enterprise_eng_ws_developer
            schema: dbt_dev
            port: 443
