name: YAML linter
description: Lints YAML files

inputs:
  dir:
    description: Directory containing dbt project
    required: true
  rules:
    description: Rules to lint with
    required: true

runs:
  using: composite
  steps:
    - name: Lint YAML files
      shell: bash
      run: |
        poetry run yamllint -c ${{ inputs.rules }} ${{ inputs.dir }}
