name: Deploy dbt worker

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the dbt workflow. Leave blank for latest.'
        type: string
      environment:
        description: 'Environment from which to fetch secrets'
        type: choice
        options:
          - stg
          - prod

env:
  http_proxy: "http://squid.internal:3128"
  https_proxy: "http://squid.internal:3128"


jobs:
  deploy:
    permissions:
      contents: write
    name: Deploy dbt worker
    environment: ${{ inputs.environment }}
    runs-on: [ self-hosted, self-hosted-linux-amd64-jammy-private-endpoint-medium ]
    timeout-minutes: 45
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        shell: bash
        run: |
            sudo snap install juju --channel=3.4/stable --classic
            sudo snap install vault
            # For YAML manipulation
            sudo snap install yq

      - name: Set up environment variables
        shell: bash
        run: |
          echo "no_proxy=radosgw.ps6.canonical.com,vault.admin.canonical.com,api.charmhub.io" >> $GITHUB_ENV
          echo "http_proxy=http://squid.internal:3128" >> $GITHUB_ENV
          echo "https_proxy=http://squid.internal:3128" >> $GITHUB_ENV

          echo "JUJU_CONTROLLER=${{ vars.JUJU_CONTROLLER }}" >> $GITHUB_ENV
          echo "JUJU_MODEL=${{ vars.JUJU_MODEL }}" >> $GITHUB_ENV

          echo "VAULT_ADDR=https://vault.admin.canonical.com:8200"  >> $GITHUB_ENV
          echo "VAULT_SECRET_PATH_ROLE=${{ vars.VAULT_SECRET_PATH_ROLE }}" >> $GITHUB_ENV

          # Find all directories containing a dbt_project.yml file
          DBT_PROJECTS=$(
            find . -type f -name dbt_project.yml -exec dirname {} \; |
            xargs -n1 basename |
            sort -u
          )
          if [ $WORKFLOW_NAME != "dbt-template" ]; then
            # Remove template from list of projects if the current repository is not the template
            DBT_PROJECTS=$(echo $DBT_PROJECTS | sed '/^template$/d')
          fi
          # use heredoc format to write multiline string to environment
          echo "DBT_PROJECTS<<EOF" >> $GITHUB_ENV
          echo "$DBT_PROJECTS" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
        env:
          WORKFLOW_NAME: ${{ github.event.repository.name }}

      - name: Get latest version tag of workflow from GitHub API
        id: get-version
        uses: ./.github/actions/get_rock_version
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Load credentials from vault
        run: bash ./.github/scripts/load-creds-lxc.sh
        shell: bash
        env:
          VAULT_APPROLE_ROLE_ID: ${{ secrets.vault_approle_role_id }}
          VAULT_APPROLE_SECRET_ID: ${{ secrets.vault_approle_secret_id }}

      - name: Deploy charm
        run: |
          bash ./.github/scripts/deploy-charm.sh
        shell: bash
        env:
          CONTAINER_URL: ghcr.io/canonical/dbt-workflow
          APP_VERSION: ${{ steps.get-version.outputs.version }}
          WORKFLOW_NAME: ${{ github.event.repository.name }}

      - name: Add auth-secrets to Juju
        id: auth-secrets
        uses: ./.github/actions/auth_secrets
        with:
          temporal-encryption-key: ${{ secrets.TEMPORAL_ENCRYPTION_KEY }}
          temporal-auth-provider: ${{ secrets.TEMPORAL_AUTH_PROVIDER }}
          temporal-service-account: ${{ secrets.TEMPORAL_OIDC }}

      - name: Add additional secrets to Juju
        id: secrets
        uses: ./.github/actions/secrets
        with:
          all-secrets: ${{ toJSON(secrets) }}
          projects: ${{ env.DBT_PROJECTS }}

      - name: Set up environment variables
        id: env-vars
        uses: ./.github/actions/env_vars
        with:
          all-vars: ${{ toJSON(vars) }}
          secret-id: ${{ steps.secrets.outputs.secret-id }}
          projects: ${{ env.DBT_PROJECTS }}

      - name: Configure Temporal worker
        id: configure-worker
        uses: ./.github/actions/configure_worker
        with:
          all-vars: ${{ toJSON(vars) }}
          version: ${{ steps.get-version.outputs.version }}
          auth-secret-id: ${{ steps.auth-secrets.outputs.secret-id }}
