# Validate YAML files
name: YAML validator

on:
  pull_request:
    branches: [ 'main' ]
  workflow_dispatch:


jobs:
  yaml_validator:
    runs-on: ubuntu-latest
    steps:
      - name: Lint YAML
        uses: actions/checkout@v3
        run: yamllint **/schedules.yaml
      - name: Validate YAML with JSON Schema
        uses: brittonhayes/validate-yaml@v0.5.1
        with:
          schemaPath: '.github/workflows/schedules_schema.json'
          files: |
            **/schedules.yaml
